config/routes.rb
#Routes for all of the models
Rails.application.routes.draw do
  resources :producers
  resources :samples
  devise_for :users
  resources :ogsongs
  #root link
  root 'home#home'
  #get and post request
    get 'contact', to: 'home#contact'
    post 'request_contact', to: 'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sample.rb
class Sample < ApplicationRecord
  #States the relationship.
  #One-to-many relationship between original song and a sample
  belongs_to :ogsong
  #Many-to-many relationship between sampled songs and producers.
  has_and_belongs_to_many :producers
    #validates the presence of the title, artist and original song of the sampled song
  validates :title, :artist, :ogsong, presence: true
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]
  before_action :set_ogsong, only:[:new, :create]
  before_action :authenticate_user!
  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = @ogsong.samples.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = @ogsong.samples.new(sample_params)

    respond_to do |format|
        #if sample created successfully, show notice
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
        #if producer updated successfully, show notice
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.js   { flash[:notice] = 'Task was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private

    def set_ogsong
      @ogsong = Ogsong.find_by(id: params[:ogsong_id]) || Ogsong.find(sample_params[:ogsong_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:ogsong_id, :title, :artist, :lyrics)
    end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.erb
<%= form_for @sample do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@sample.errors.count, "error")} prohibited this sample from being saved:" %>
      </h2>
      <ul>
        <% @sample.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%# Form fields to input data entry %>
  <%# title of the sampled song %>
  <div class="field">
    <%= f.label :ogsong %>
    <p><%= f.hidden_field :ogsong_id, value: @sample.ogsong.id %></p>
  </div>
        <%# title of the sampled song %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
      <%# artist of the sampled song %>
  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>
        <%# lyrics of the sampled song %>
  <div class="field">
    <%= f.label :lyrics %>
    <%= f.text_area :lyrics %>
  </div>
    <%# Save button %>
  <div class="actions">
<%= submit_tag("Save", { :name => 'save', :id => 'save', :type => 'save', :class => 'btn btn-success'}) %>
  </div>
      <%# Clears the form fields %>
  <div id = "reset">
    <%= submit_tag("Reset", { :name => 'reset', :id => 'reset', :type => 'reset', :class => 'btn btn-default'}) %>
  </div>
<% end %>

app/views/samples/destroy.js.erb
$('#sample_<%= @sample.id %>').hide();
console.log("deleted")

app/views/samples/edit.html.erb
  <%# Renders the form to allow the already made data to be edited %>
<h1><%= t('.editSample') %></h1>
<%= render 'form' %>
<%= link_to 'Show', @sample %>

<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<h1><%= t('.listSample') %></h1>
<%# Search bar to filter the data %>
<input id="myInput" type="text" placeholder="Search..">
<table>
  <thead>
    <tr>
      <th><%= t('.ogsong') %></th>
      <th><%= t('.title') %></th>
      <th><%= t('.artist') %></th>
      <th><%= t('.lyrics') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody id = "List">
    <% @samples.each do |sample| %>
      <tr>
        <td>
          <%# Title of original song of the sampled %>
          <%= sample.ogsong.title %>
        </td>
        <td>
          <%# Title of sampled song %>
          <%= sample.title %>
        </td>
        <td>
          <%# artist of sampled song %>
          <%= sample.artist %>
        </td>
        <td>
          <%# lyrics of sampled song %>
          <%= sample.lyrics %>
        </td>
        <%# Link to show the specific song %>
        <td>
          <%= link_to 'Show', sample %>
        </td>

    <% end %>


  </tbody>
</table>
<br/>

app/views/samples/new.html.erb
  <%# Renders the form to allow a new data entry %>
<h1><%= t('.newSample') %></h1>
<%= render 'form' %>
<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<br>
<br>
  <%# Shows the data entry %>
<p>
      <%# Title of original song the sampled song sampled off of %>
  <b><%= t('.ogsong') %></b>
  <%= @sample.ogsong.title %>
</p>
<p>
      <%# Title of sampled song %>
  <b><%= t('.title') %></b>
  <%= @sample.title %>
</p>
<p>
      <%# Artist of sampled song %>
  <b><%= t('.artist') %></b>
  <%= @sample.artist %>
</p>
<p>
      <%# Lyrics of sampled song %>
  <b><%= t('.lyrics') %></b>
  <%= @sample.lyrics %>
</p>
<p>
      <%# Prints all producers that contributed to the sampled song %>
<b><%= t('.producer') %></b>
<% @sample.producers.each do |producer| %>
<%= producer.name %>
<% end %>
</p>
<%= link_to 'Edit', edit_sample_path(@sample) %>

<%= link_to 'Back', samples_path %>