config/routes.rb
#Routes for all of the models
Rails.application.routes.draw do
  resources :producers
  resources :samples
  devise_for :users
  resources :ogsongs
  #root link
  root 'home#home'
  #get and post request
    get 'contact', to: 'home#contact'
    post 'request_contact', to: 'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ogsong.rb
class Ogsong < ApplicationRecord
  #States the relationship.
  #One-to-many relationship between original song and a sample
  has_many :samples, dependent: :destroy
  #Many-to-many relationship between original songs and producers.
  has_and_belongs_to_many :producers
  #validates the presence of the title of the song
  validates :title, presence: true
  #validates the uniquenessof the title
  validates :title, uniqueness: true
end

app/controllers/ogsongs_controller.rb
class OgsongsController < ApplicationController
  before_action :set_ogsong, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /ogsongs
  # GET /ogsongs.json
  def index
    @ogsongs = Ogsong.all
  end

  # GET /ogsongs/1
  # GET /ogsongs/1.json
  def show
  end

  # GET /ogsongs/new
  def new
    @ogsong = Ogsong.new
  end

  # GET /ogsongs/1/edit
  def edit
  end

  # POST /ogsongs
  # POST /ogsongs.json
  def create
    @ogsong = Ogsong.new(ogsong_params)

    respond_to do |format|
      #if ogsong created successfully, show notice
      if @ogsong.save
        format.html { redirect_to @ogsong, notice: 'Ogsong was successfully created.' }
        format.json { render :show, status: :created, location: @ogsong }
      else
        format.html { render :new }
        format.json { render json: @ogsong.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ogsongs/1
  # PATCH/PUT /ogsongs/1.json
  def update
    respond_to do |format|
      if @ogsong.update(ogsong_params)
        #if ogsong updated successfull, show notice
        format.html { redirect_to @ogsong, notice: 'Ogsong was successfully updated.' }
        format.json { render :show, status: :ok, location: @ogsong }
      else
        format.html { render :edit }
        format.json { render json: @ogsong.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ogsongs/1
  # DELETE /ogsongs/1.json
  def destroy
    @ogsong.destroy
    respond_to do |format|
      format.html { redirect_to ogsongs_url, notice: 'Ogsong was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ogsong
      @ogsong = Ogsong.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ogsong_params
      params.require(:ogsong).permit(:title, :artist, :lyrics)
    end
end

app/helpers/ogsongs_helper.rb
module OgsongsHelper
end

app/views/ogsongs/_form.html.erb
<%= form_for @ogsong do |f| %>
  <% if @ogsong.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@ogsong.errors.count, "error")} prohibited this ogsong from being saved:" %>
      </h2>
      <ul>
        <% @ogsong.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# Form fields to input data entry %>
  <%# title of the original song %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
    <%# artist of the original song %>
  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist%>
  </div>
    <%# lyrics of the original song %>
  <div class="field">
    <%= f.label :lyrics %>
    <%= f.text_area :lyrics %>
  </div>
  <div class="actions">
      <%# Save button %>
<%= submit_tag("Save", { :name => 'save', :id => 'save', :type => 'save', :class => 'btn btn-success'}) %>
  </div>
    <%# Clears the form fields %>
  <div id = "reset">
    <%= submit_tag("Reset", { :name => 'reset', :id => 'reset', :type => 'reset', :class => 'btn btn-default'}) %>
  </div>
<% end %>

app/views/ogsongs/edit.html.erb
  <%# Renders the form to allow the already made data to be edited %>
<h1><%= t('.test') %></h1>
<%= render 'form' %>
<%= link_to 'Show', @ogsong %>

<%= link_to 'Back', ogsongs_path %>

app/views/ogsongs/index.html.erb
  <%# Creates a table of data %>
<br/>
<h1><%= t('.listing_test') %></h1>
  <%# Search bar to filter the data %>
<input id="myInput" type="text" placeholder="Search..">
<table>
  <thead>
    <tr>
      <th><%= t('.title') %></th>
      <th><%= t('.artist') %></th>
      <th><%= t('.lyrics') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody id = "List">
    <% @ogsongs.each do |ogsong| %>
      <tr>
        <%# Title of original song %>
        <td>
          <%= ogsong.title %>
        </td>
        <%# artist of original song %>
        <td>
          <%= ogsong.artist %>
        </td>
        <%# Lyrics of original song %>
        <td>
          <%= ogsong.lyrics %>
        </td>
        <%# Link to show the specific song %>
        <td>
          <%= link_to 'Show', ogsong %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%# Create new original song %>
<%= link_to 'New Ogsong', new_ogsong_path %>

app/views/ogsongs/new.html.erb
  <%# Renders the form to allow a new data entry %>
<h1><%= t('.newOg') %></h1>
<%= render 'form' %>
<%= link_to 'Back', ogsongs_path %>

app/views/ogsongs/show.html.erb
<br>
<br>
  <%# Shows the data entry %>
<p>
    <%# Original song title %>
  <b><%= t('.title') %></b>
  <%= @ogsong.title %>
</p>
<p>
    <%# Artist of original song %>
  <b><%= t('.artist') %></b>
  <%= @ogsong.artist %>
</p>
<p>
    <%# Lyrics of original song %>
  <b><%= t('.lyrics') %></b>
  <%= @ogsong.lyrics %>
</p>
<p>
    <%# Name of the song producer %>
<b><%= t('.producer') %></b>
<% @ogsong.producers.each do |producer| %>
<%= producer.name %>
<% end %>
</p>
<p><%= t('.sample') %></p>
<table>
  <tbody>
      <%# Prints each song that has sampled from the original song %>
    <% @ogsong.samples.each do |sample| %>
    <tr id = "sample_<%= sample.id %>">
      <td>
        <%= sample.title %>
      </td>
      <td>
        <%= link_to 'Show', sample %>
      </td>

    </tr>
    <% end %>
  </tbody>
</table>

  <%# Link to new sample song %>
<p><%= link_to 'Add Sample', new_sample_path(ogsong_id: @ogsong) %></p>
  <%# Link to edit original song %>
<%= link_to 'Edit', edit_ogsong_path(@ogsong) %>
  <%# Link to all original songs %>
<%= link_to 'Back', ogsongs_path %>