config/routes.rb
#Routes for all of the models
Rails.application.routes.draw do
  resources :producers
  resources :samples
  devise_for :users
  resources :ogsongs
  #root link
  root 'home#home'
  #get and post request
    get 'contact', to: 'home#contact'
    post 'request_contact', to: 'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/producer.rb
class Producer < ApplicationRecord
    #Many-to-many relationship between original songs and producers.
  has_and_belongs_to_many :ogsongs
    #Many-to-many relationship between sampled songs and producers.
  has_and_belongs_to_many :samples
    #validates the presence of the name of the song
  validates :name, presence: true
    #validates the uniqueness of the name of the song
  validates :name, uniqueness: true
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  before_action :set_producer, only: [:show, :edit, :update, :destroy]

  # GET /producers
  # GET /producers.json
  def index
    @producers = Producer.all
  end

  # GET /producers/1
  # GET /producers/1.json
  def show
  end

  # GET /producers/new
  def new
    @producer = Producer.new
  end

  # GET /producers/1/edit
  def edit
  end

  # POST /producers
  # POST /producers.json
  def create
    @producer = Producer.new(producer_params)

    respond_to do |format|
  #if producer created successfully, show notice
      if @producer.save
        format.html { redirect_to @producer, notice: 'Producer was successfully created.' }
        format.json { render :show, status: :created, location: @producer }
      else
        format.html { render :new }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producers/1
  # PATCH/PUT /producers/1.json
  def update
    respond_to do |format|
        #if producer updated successfully, show notice
      if @producer.update(producer_params)
        format.html { redirect_to @producer, notice: 'Producer was successfully updated.' }
        format.json { render :show, status: :ok, location: @producer }
      else
        format.html { render :edit }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.json
  def destroy
    @producer.destroy
    respond_to do |format|
      format.html { redirect_to producers_url, notice: 'Producer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producer
      @producer = Producer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producer_params
      params.require(:producer).permit(:name, :email, :telephone)
    end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.erb
<%= form_for @producer do |f| %>
  <% if @producer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@producer.errors.count, "error")} prohibited this producer from being saved:" %>
      </h2>
      <ul>
        <% @producer.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# Form fields to input data entry %>
  <%# title of the producers %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%# email of the producer %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <%# telephone of the producer %>
  <div class="field">
    <%= f.label :telephone %>
    <%= f.text_field :telephone %>
  </div>
  <%# Save button %>
  <div class="actions">
<%= submit_tag("Save", { :name => 'save', :id => 'save', :type => 'save', :class => 'btn btn-success'}) %>
  </div>
      <%# Clears the form fields %>
  <div id = "reset">
    <%= submit_tag("Reset", { :name => 'reset', :id => 'reset', :type => 'reset', :class => 'btn btn-default'}) %>
  </div>

<% end %>

app/views/producers/edit.html.erb
  <%# Renders the form to allow the already made data to be edited %>
<h1><%= t('.edit_test') %></h1>
<%= render 'form' %>
<%= link_to 'Show', @producer %>

<%= link_to 'Back', producers_path %>

app/views/producers/index.html.erb
<h1><%= t('.list') %></h1>
<%# Search bar to filter the data %>
<input id="myInput" type="text" placeholder="Search..">
<table>
  <thead>
    <tr>
      <th><%= t('.name') %></th>
      <th><%= t('.email') %></th>
      <th><%= t('.tele') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody id = "List">
    <% @producers.each do |producer| %>
      <tr>
        <td>
          <%# Name of producer %>
          <%= producer.name %>
        </td>
        <td>
          <%# Producer email %>
          <%= producer.email %>
        </td>
        <td>
        <%# Telephone of producer %>
          <%= producer.telephone %>
        </td>
        <%# Link to show the specific producer %>
        <td>
          <%= link_to 'Show', producer %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%# Create new producer %>
<%= link_to 'New Producer', new_producer_path %>

app/views/producers/new.html.erb
  <%# Renders the form to allow a new data entry %>
<h1><%= t('.newPro') %></h1>
<%= render 'form' %>
<%= link_to 'Back', producers_path %>

app/views/producers/show.html.erb
<p id="notice">
  <%= notice %>
</p>
  <%# Shows the data entry %>
<p>
      <%# Name of producer %>
  <b><%= t('.name') %></b>
  <%= @producer.name %>
</p>
<p>
      <%# Email of producer %>
  <b><%= t('.email') %></b>
  <%= @producer.email %>
</p>
<p>
      <%# Telephone of producer %>
  <b><%= t('.tele') %></b>
  <%= @producer.telephone %>
</p>

<table>
  <tbody>
        <%# Prints all original songs producer has worked on %>
    <% @producer.ogsongs.each do |ogsong| %>
    <tr id = "ogsong_<%= ogsong.id %>">
      <td>
        <%= ogsong.title %>
      </td>
      <td>
        <%= ogsong.artist %>
      </td>
      <td>
        <%= link_to 'Show', ogsong %>
      </td>
      <td>
        <%= link_to 'Edit', edit_ogsong_path(ogsong) %>
      </td>
      <td>
        <%= link_to 'Destroy', ogsong, :method => :delete, :data => {:confirm => 'Are you sure?'}, :remote => true %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_producer_path(@producer) %>

<%= link_to 'Back', producers_path %>